Repository ZB-Online/Kanban, pull requests merged in 2021-12, with the labels that each got.

#5 #3 page-layout added
  public/css/style.css
  public/index.html
Labels: reviewMe

#6 Feature/1 column layout
  public/css/style.css
  public/index.html
Labels: enhancement, reviewMe

#4 #2 Feat kanban layout
  .DS_Store
  public/app.js
  public/css/style.css
  public/index.html
Labels: reviewMe

#11 #10 Fix note layout
  public/css/style.css
  public/index.html
Labels: invalid, reviewMe

#12 #7 feat server-api
  .eslintrc.json
  package-lock.json
  package.json
  public/index.html
  public/utils/fetch.js
  server.js
Labels: enhancement

#14 #13 feat add note
  public/css/style.css
  public/index.html
Labels: enhancement

#15 Feature/9 notes dragdrop
  public/app.js
  public/css/style.css
  public/index.html
  public/note.js
Labels: enhancement
